version: "3"
services:
  redis:
    image: redis:6.2
    hostname: roc-redis
    container_name: roc-redis
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: roc-minio
    hostname: roc-minio
    environment:
      MINIO_ROOT_USER: "roc"
      MINIO_ROOT_PASSWORD: "roc-minio-pwd"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - data:/data
  roc-platform:
    build:
      context: .
      dockerfile: ./platform/Dockerfile
    container_name: roc-platform
    hostname: roc-platform
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - minio
    environment:
      DATASOURCE_HOST: roc-mysql
      DATASOURCE_PORT: 3306
      DATASOURCE_DB: roc_dev_db
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: my-secret-pw
      STOMP_HOST: roc-rabbitmq
      STOMP_PORT: 61613
      ROC_GIT_REPOSITORY_DIR: /home/git/roc
      ROC_S3_HOST: roc-minio
      ROC_S3_PORT: 9000
      ROC_S3_USER: roc
      ROC_S3_PWD: roc-minio-pwd
  roc-nginx:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: roc-nginx
    hostname: roc-nginx
    restart: on-failure
    ports:
      - "8000:80"
volumes:
  data: