FROM golang:1.18-alpine AS build

WORKDIR /src

RUN apk --no-cache add git gcc
ADD . /src

RUN go get -d -v ./...
RUN go build -o roc-platform cmd/platform/*.go


FROM alpine
WORKDIR /app
COPY --from=build /src/roc-platform /app/
ENTRYPOINT ./roc-platform
