version: "3"
services:
  mysql:
    container_name: roc-mysql
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
  redis:
    image: 'redis:alpine'
    restart: always
    hostname: redis
    container_name: roc-redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass adminadmin
  rabbitmq:
    build:
      context: .
      dockerfile: ./platform/src/main/resources/docker/rabbitmq/Dockerfile
    restart: always
    container_name: roc-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "roc"
      RABBITMQ_DEFAULT_PASS: "roc"
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "15674:15674"
      - "61613:61613"