FROM node:16-alpine

WORKDIR /usr/src/platform

RUN npm install -g lerna
COPY . .

COPY package*.json ./
RUN npm install -ws

RUN lerna run build
RUN rm -fr ./packages/**/src

EXPOSE 3000
CMD [ "node", "packages/platform/lib/main.js" ]