version: "3"
services:
  mysql:
    image: mysql:8
    hostname: roc-mysql
    container_name: roc-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=roc_dev_db
  redis:
    image: 'redis:alpine'
    hostname: roc-redis
    container_name: roc-redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass adminadmin
  rabbitmq:
    build:
      context: .
      dockerfile: ./platform/src/main/resources/docker/rabbitmq/Dockerfile
    container_name: roc-rabbitmq
    hostname: roc-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "roc"
      RABBITMQ_DEFAULT_PASS: "roc"
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "15674:15674"
      - "61613:61613"
  roc-platform:
    build:
      context: .
      dockerfile: ./platform/Dockerfile
    container_name: roc-platform
    hostname: roc-platform
    restart: on-failure
    volumes:
      - "/Users/yusuf/Desktop/roc:/home/git/roc"
    ports:
      - "8080:8080"
      - "221:22"
    depends_on:
      - redis
      - rabbitmq
      - mysql
    environment:
      DATASOURCE_HOST: roc-mysql
      DATASOURCE_PORT: 3306
      DATASOURCE_DB: roc_dev_db
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: my-secret-pw
      STOMP_HOST: roc-rabbitmq
      STOMP_PORT: 61613
      ROC_GIT_REPOSITORY_DIR: /home/git/roc
