FROM golang:1.18-alpine

WORKDIR app

COPY . .

# Download all the dependencies
RUN go get -d -v ./...

# Install the package
RUN go build -o ws-tunnel cmd/ws-tunnel/main.go

EXPOSE 8080

CMD ["./ws-tunnel"]
