FROM node:16-alpine

WORKDIR /usr/src/platform

RUN npm install -g lerna
COPY . .

COPY package*.json ./
RUN npm install -ws

RUN lerna run build
RUN rm -fr ./packages/**/src

EXPOSE 5000
CMD [ "node", "packages/tunnel/lib/index.js" ]
