version: "3"
services:
  redis:
    image: redis:6.2
    hostname: roc-redis
    container_name: roc-redis
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: roc-minio
    hostname: roc-minio
    environment:
      MINIO_ROOT_USER: "roc"
      MINIO_ROOT_PASSWORD: "roc-minio-pwd"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - data:/data
  roc-platform:
    build:
      context: .
      dockerfile: ./Dockerfile.platform
    container_name: roc-platform
    hostname: roc-platform
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://roc-redis:6379
      S3_URL: minio://roc:roc-minio-pwd@roc-minio:9000
  roc-tunnel:
    build:
      context: .
      dockerfile: ./Dockerfile.ws-tunnel
    container_name: roc-tunnel
    hostname: roc-tunnel
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_URL: roc-redis:6379
  roc-nginx:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: roc-nginx
    hostname: roc-nginx
    restart: on-failure
    ports:
      - "8080:80"
volumes:
  data: