apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: platform
      image: nginx:1.14.2
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: roc-tunnel
      image: nginx:1.14.2
      ports:
        - containerPort: 80
