/*
 * ROC (Robot Operation Center)
 *
 * K8s Native Automation Platform tailored for Robot Framework script execution. Provides parallelization and centralized reporting by desing. 🤖
 *
 * API version: 2.0.0
 * Contact: yusufcanbayrak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

type InlineResponse200 struct {
	ProjectId     string `json:"projectId,omitempty"`
	EnvironmentId string `json:"environmentId,omitempty"`
}
