/*
 * ROC (Robot Operation Center)
 *
 * K8s Native Automation Platform tailored for Robot Framework script execution. Provides parallelization and centralized reporting by desing. 🤖
 *
 * API version: 2.0.0
 * Contact: yusufcanbayrak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

type TaskForce struct {
	// Unique identifier of task force
	Id string `json:"id,omitempty"`
	// The name of the top-level task suite
	Name string `json:"name,omitempty"`
	// Project id of the environment
	ProjectId string `json:"projectId,omitempty"`
	// Detailed description of the task force's purpose
	Description string `json:"description,omitempty"`
	// Git repository url of the Robot Framework project
	Repository string `json:"repository,omitempty"`
	// Docker image for execution environment
	Runner string `json:"runner,omitempty"`
	// Regex pattern to filter robots to be executed
	Selector string `json:"selector,omitempty"`
	// Include tag pattern for robot scripts
	Include string `json:"include,omitempty"`
	// Tags for labelling the task force
	Tags []string `json:"tags,omitempty"`
}
