/*
 * ROC (Robot Operation Center)
 *
 * K8s Native Automation Platform tailored for Robot Framework script execution. Provides parallelization and centralized reporting by desing. 🤖
 *
 * API version: 2.0.0
 * Contact: yusufcanbayrak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

type Job struct {
	// Job identifier (generated value)
	Id string `json:"id,omitempty"`
	// Project id of the Job object
	ProjectId   string       `json:"projectId,omitempty"`
	TaskForce   *TaskForce   `json:"taskForce,omitempty"`
	Environment *Environment `json:"environment,omitempty"`
	Status      *JobStatus   `json:"status,omitempty"`
	Result      *JobResult   `json:"result,omitempty"`
}
