name: cli
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.java'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.java'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - run: npm install
        working-directory: ./cli
      - run: npm run build
        working-directory: ./cli
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - run: npm install
        working-directory: ./cli
      - run: npm run lint
        working-directory: ./cli       

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - run: npm install
        working-directory: ./cli
      - run: echo "{\"rocUrl\":\"https://example-platform.com\",\"defaultProject\":null}" > ~/.roc.json
        working-directory: ./cli
      - run: npm run test
        working-directory: ./cli   
