name: Build Docker Images

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create roc-platform image
      # You may pin to the exact commit or the version.
      # uses: craftech-io/package-action@009001a7fd1c4f139ae06aeceed9b679daf52734
      uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        context: ./platform
        image_name: roc-platform
        dockerfile: ./platform/Dockerfile
        
    - name: Create roc-web image   
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm install
      working-directory: ./web
    - run: npm run build
      working-directory: ./web
    - name: Docker Package Registry
      # You may pin to the exact commit or the version.
      # uses: craftech-io/package-action@009001a7fd1c4f139ae06aeceed9b679daf52734
      uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        context: ./web
        image_name: roc-web
        dockerfile: ./web/Dockerfile
