# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Docker Package Registry
      # You may pin to the exact commit or the version.
      # uses: craftech-io/package-action@009001a7fd1c4f139ae06aeceed9b679daf52734
      uses: craftech-io/package-action@v3.1.0
      with:
        # GitHub Repository Token to log in using.
        access_token: ${{ secrets.GITHUB_TOKEN }}
        # Where should GitHub Docker find the Dockerfile, relative to the root of the repository.
        context: ./platform
        image_name: roc-platform
        dockerfile: ./platform/Dockerfile
