name: Typescript Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
        working-directory: ./web
      - run: npm run build
        working-directory: ./web
      - name: Docker Package Registry
        # You may pin to the exact commit or the version.
        # uses: craftech-io/package-action@009001a7fd1c4f139ae06aeceed9b679daf52734
        uses: craftech-io/package-action@v3.1.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ github.branch }}
          context: ./web
          image_name: roc-web
          dockerfile: ./web/Dockerfile
