name: Typescript Build
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.java'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.java'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
        working-directory: ./cli
      - run: npm run build
        working-directory: ./cli
