name: Typescript Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/upload-artifact@v2
        with:
          name: ci-build
          path: ./web/build/
      - run: cd web/
      - run: npm install
      - run: npm build
