name: platform

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18
          # Path to the go.mod file.
      - name: Install Dependencies
        run: go get -d -v ./...
      - name: Build Platform
        run: go build -o roc-platform cmd/platform/*.go
