name: platform

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Platform
      run: go build -v ./cmd/platform/...
      
    - name: Build Agent
      run: go build -v ./cmd/agent/...

