name: platform

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Platform
      run: go build -v ./cmd/platform/...
      
    - name: Build Agent
      run: go build -v ./cmd/agent/...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6
    - name: Unit Tests
      run: go test -timeout 30s ./...
